const ACTION_TYPES = {
  AUTH: {
    SET_IS_LOGIN: 'SET_IS_LOGIN',
  },
  THEME: {
    CHANGE_THEME: 'CHANGE_THEME',
    SET_DEFAULT_THEME: 'SET_DEFAULT_THEME',
  },
  MOVIES: {
    GET_MOVIES_START: 'GET_MOVIES_START',
    GET_MOVIES_FAILED: 'GET_MOVIES_FAILED',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  },
};

export {ACTION_TYPES};
